# Generated by Django 5.0 on 2024-01-20 15:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_remove_scrapedproduct_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
