# Generated by Django 5.0 on 2024-01-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedproduct',
            name='sell_price',
            field=models.FloatField(),
        ),
    ]
