# Generated by Django 5.0 on 2024-01-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_scrapingtask_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingtask',
            name='product_id',
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='products_ids_list',
            field=models.TextField(null=True),
        ),
    ]
