# Generated by Django 5.0 on 2023-12-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description_name', models.CharField(max_length=255)),
                ('sell_price', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('brand_name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
            ],
        ),
    ]
